# Project information
site_name: Nik Moores
site_url: https://nikmoores.com
site_author: Nik Moores

# Copyright
copyright: Copyright &copy; 2021 - 2022 Nik Moores

# Repository
repo_name: "GitHub"
repo_url: "https://github.com/Adroz/manager-toolkit"

#Theming
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.sections

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - toc:
      toc_depth: 5
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true

# Plugins
plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Adroz
      name: GitHub
    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/in/nik-moores
      name: LinkedIn